

services:
  db:
    image: postgres:16
    restart: always
    container_name: conteiner_db
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      # Variables de entorno para la base de datos
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      # Guarda la data en en volumen del disco local para la persistencia de datos
      - ./postgresdb:/var/lib/postgresql/data
    networks:
      - asistente_network

networks:
  asistente_network:
    driver: bridge
